language: java
sudo: false
jdk:
  # - openjdk8 # add when openjdk8 is also supported
  - oraclejdk8
branches:
  only:
  - master
script: "mvn verify"
# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=
after_success:
  - bash <(curl -s https://codecov.io/bash)
